steps:
- name: node:10.0.0
  entrypoint: npm
  args: ['install']

- name: node:10.0.0
  entrypoint: npm
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project', 'weekly-summary']

- name: 'gcr.io/cloud-builders/curl'
  args: ['https://weekly-summary.appspot.com']

timeout: '600s'
